/** Quiet Premium V5 isolated travel-strategy engine — 5.0-alpha.3 (2026-09-17)
 * Not wired to diagnostic.html or any customer-facing page.
 * Facts determine opportunity. Constraints determine feasibility.
 * Aspirations determine presentation order only. Benefits stay visible even
 * when they receive little/no internal recommendation credit.
 */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.QuietPremiumEngineV5=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const ENGINE_VERSION='5.0-alpha.3',RULES_AS_OF='2026-09-17',CATS=['dining','grocery','airfare','hotel','general'];
const n=v=>{if(typeof v==='number')return Number.isFinite(v)?v:0;const x=Number(String(v??'').replace(/[$,%\s,]/g,''));return Number.isFinite(x)?x:0};
const s=v=>String(v??'').trim(),lc=v=>s(v).toLowerCase(),sum=a=>(a||[]).reduce((x,y)=>x+(+y||0),0),uniq=a=>[...new Set((a||[]).filter(Boolean))],cl=(x,a,b)=>Math.max(a,Math.min(b,+x||0)),cp=x=>JSON.parse(JSON.stringify(x)),rnd=(x,d=0)=>{const p=10**d;return Math.round((+x||0)*p)/p};
const A=(tier,amount)=>({tier,amount}),H=(tier,nights)=>({tier,nights});
const RULES=Object.freeze({
 meta:{version:ENGINE_VERSION,asOf:RULES_AS_OF,supportedAirlines:['delta','united','american','southwest'],supportedHotels:['hyatt','marriott','hilton'],supportedFlexible:['amex_mr','chase_ur','capital_one_miles']},
 airlines:{
  delta:{metric:'MQD',thresholds:[A('Silver Medallion',5000),A('Gold Medallion',10000),A('Platinum Medallion',15000),A('Diamond Medallion',28000)]},
  united:{metric:'PQP',thresholds:[A('Premier Silver',6000),A('Premier Gold',12000),A('Premier Platinum',18000),A('Premier 1K',28000)]},
  american:{metric:'Loyalty Points',thresholds:[A('AAdvantage Gold',40000),A('AAdvantage Platinum',75000),A('AAdvantage Platinum Pro',125000),A('AAdvantage Executive Platinum',200000)]},
  southwest:{metric:'TQP',thresholds:[A('A-List',35000),A('A-List Preferred',70000)],flightThresholds:[{tier:'A-List',flights:20},{tier:'A-List Preferred',flights:40}]}
 },
 hotels:{
  hyatt:{thresholds:[H('Discoverist',10),H('Explorist',30),H('Globalist',60)]},
  marriott:{thresholds:[H('Silver Elite',10),H('Gold Elite',25),H('Platinum Elite',50),H('Titanium Elite',75)]},
  hilton:{thresholds:[{tier:'Silver',nights:10,stays:4,spend:2500},{tier:'Gold',nights:25,stays:15,spend:6000},{tier:'Diamond',nights:50,stays:25,spend:11500}],diamondReserve:{tier:'Diamond Reserve',nights:80,stays:40,spend:18000}}
 },
 cards:{
  amex_gold:{label:'American Express Gold Card',currency:'amex_mr',annualFee:325,earn:{dining:4,grocery:4,airfare:3,hotel:1,general:1},caps:{dining:50000,grocery:25000}},
  amex_platinum:{label:'The Platinum Card from American Express',currency:'amex_mr',annualFee:895,earn:{dining:1,grocery:1,airfare:5,hotel:1,general:1},caps:{airfare:500000},benefitTags:['lounge','premium_hotel_booking']},
  chase_preferred:{label:'Chase Sapphire Preferred',currency:'chase_ur',annualFee:95,earn:{dining:3,grocery:1,airfare:2,hotel:2,general:1},verificationPending:true},
  chase_reserve:{label:'Chase Sapphire Reserve',currency:'chase_ur',annualFee:795,earn:{dining:3,grocery:1,airfare:4,hotel:4,general:1},benefitTags:['lounge','travel_credit']},
  venture:{label:'Capital One Venture Rewards',currency:'capital_one_miles',annualFee:95,earn:{dining:2,grocery:2,airfare:2,hotel:2,general:2}},
  venture_x:{label:'Capital One Venture X Rewards',currency:'capital_one_miles',annualFee:395,earn:{dining:2,grocery:2,airfare:2,hotel:2,general:2},benefitTags:['lounge','travel_credit','anniversary_miles']},
  delta_platinum:{label:'Delta SkyMiles Platinum American Express Card',currency:'skymiles',annualFee:350,earn:{dining:2,grocery:2,airfare:3,hotel:3,general:1},airline:'delta',status:{headstart:2500,spendDivisor:20},benefitTags:['companion_certificate_renewal']},
  delta_reserve:{label:'Delta SkyMiles Reserve American Express Card',currency:'skymiles',annualFee:650,earn:{dining:1,grocery:1,airfare:3,hotel:1,general:1},airline:'delta',status:{headstart:2500,spendDivisor:10},benefitTags:['lounge','upgrade_priority','companion_certificate_renewal']},
  united_explorer:{label:'United Explorer Card',currency:'united_miles',annualFee:150,earn:{dining:2,grocery:1,airfare:3,hotel:2,general:1},airline:'united',status:{spendDivisor:20,annualCap:1000},verificationPending:true},
  united_quest:{label:'United Quest Card',currency:'united_miles',annualFee:350,earn:{dining:2,grocery:1,airfare:4,hotel:2,general:1},airline:'united',status:{spendDivisor:20,annualCap:18000,annualBonus:1000}},
  united_club:{label:'United Club Card',currency:'united_miles',annualFee:695,earn:{dining:2,grocery:1,airfare:5,hotel:2,general:1},airline:'united',status:{spendDivisor:15,annualCap:28000,annualBonus:1500},benefitTags:['lounge']},
  aa_executive:{label:'Citi / AAdvantage Executive World Legend Mastercard',currency:'aadvantage',annualFee:695,earn:{dining:1,grocery:1,airfare:4,hotel:1,general:1},airline:'american',status:{lpPerEligiblePurchaseDollar:1},benefitTags:['lounge','priority_airport']},
  southwest_priority:{label:'Southwest Rapid Rewards Priority Credit Card',currency:'southwest_points',annualFee:229,earn:{dining:2,grocery:1,airfare:4,hotel:1,general:1},airline:'southwest',status:{spendBlock:5000,tqpPerBlock:2500},verificationPending:true},
  hyatt_consumer:{label:'World of Hyatt Credit Card',currency:'hyatt_points',annualFee:95,earn:{dining:2,grocery:1,airfare:2,hotel:4,general:1},hotel:'hyatt',hotelStatus:{automaticTier:'Discoverist',annualNights:5,spendBlock:5000,nightsPerBlock:2}},
  marriott_boundless:{label:'Marriott Bonvoy Boundless Credit Card',currency:'marriott_points',annualFee:95,earn:{dining:2,grocery:2,airfare:2,hotel:6,general:2},hotel:'marriott',hotelStatus:{automaticTier:'Silver Elite',annualNights:15},verificationPending:true},
  marriott_brilliant:{label:'Marriott Bonvoy Brilliant American Express Card',currency:'marriott_points',annualFee:650,earn:{dining:3,grocery:2,airfare:3,hotel:6,general:2},hotel:'marriott',hotelStatus:{automaticTier:'Platinum Elite',annualNights:25},benefitTags:['premium_hotel_benefits']},
  hilton_no_fee:{label:'Hilton Honors American Express Card',currency:'hilton_points',annualFee:0,earn:{dining:5,grocery:5,airfare:3,hotel:7,general:3},hotel:'hilton',hotelStatus:{automaticTier:'Silver'}},
  hilton_surpass:{label:'Hilton Honors American Express Surpass Card',currency:'hilton_points',annualFee:150,earn:{dining:6,grocery:6,airfare:3,hotel:12,general:3},hotel:'hilton',hotelStatus:{automaticTier:'Gold'}},
  hilton_aspire:{label:'Hilton Honors American Express Aspire Card',currency:'hilton_points',annualFee:550,earn:{dining:7,grocery:3,airfare:7,hotel:14,general:3},hotel:'hilton',hotelStatus:{automaticTier:'Diamond'},benefitTags:['premium_hotel_benefits']}
 }});
const VALUATIONS={
 conservative:{amex_mr:.0125,chase_ur:.0125,capital_one_miles:.010,skymiles:.012,united_miles:.012,aadvantage:.013,southwest_points:.013,hyatt_points:.017,marriott_points:.007,hilton_points:.005},
 base:{amex_mr:.020,chase_ur:.020,capital_one_miles:.017,skymiles:.015,united_miles:.017,aadvantage:.018,southwest_points:.014,hyatt_points:.022,marriott_points:.009,hilton_points:.008},
 upper:{amex_mr:.024,chase_ur:.024,capital_one_miles:.020,skymiles:.018,united_miles:.021,aadvantage:.022,southwest_points:.016,hyatt_points:.026,marriott_points:.011,hilton_points:.010}}
const MODEL={maxPortfolioCards:4,maxNewCardsDefault:2,materialTravelValue:400,materialCashImprovement:300,minFlightsForStatus:8,minHotelNightsForStatus:8,minAirlineShare:.55,minHotelShare:.45,complexityPenaltyPerCard:1.25,complexityPenaltyPerCurrency:.75,statusOpportunityCostLimit:900,incrementalTravelValuePerExtraCard:750,unsupportedMaterialSpendShare:.10};
const ALIASES=[
 ['hilton_aspire',['hilton honors american express aspire','hilton aspire']],['hilton_surpass',['hilton honors american express surpass','hilton surpass']],['hilton_no_fee',['hilton honors american express card','hilton honors american express']],['marriott_brilliant',['marriott bonvoy brilliant']],['marriott_boundless',['marriott bonvoy boundless']],['delta_reserve',['delta skymiles reserve','delta reserve']],['delta_platinum',['delta skymiles platinum','delta platinum']],['united_club',['united club']],['united_quest',['united quest']],['united_explorer',['united explorer']],['aa_executive',['aadvantage executive','american airlines executive','citi / aadvantage executive']],['southwest_priority',['southwest rapid rewards priority','southwest priority']],['hyatt_consumer',['world of hyatt credit card','world of hyatt card']],['amex_platinum',['platinum card from american express','american express platinum','amex platinum']],['amex_gold',['american express gold','amex gold']],['chase_reserve',['chase sapphire reserve','sapphire reserve']],['chase_preferred',['chase sapphire preferred','sapphire preferred']],['venture_x',['capital one venture x','venture x']],['venture',['capital one venture rewards','capital one venture']]];
function matchCard(v){const x=lc(v);if(!x)return null;if(RULES.cards[x])return x;for(const [id,a] of ALIASES)if(a.some(z=>x.includes(z)))return id;return null}
function spend(raw={}){const x=raw.spend||raw;return{dining:n(x.dining??raw.dining_spend),grocery:n(x.grocery??raw.grocery_spend),airfare:n(x.airfare??raw.household_airfare_spend??raw.airfare_spend),hotel:n(x.hotel??raw.hotel_spend),general:n(x.general??raw.general_spend)}}
function routing(raw,sp){const src=raw.currentRouting||raw.current_routing||{},out={};for(const c of CATS){out[c]=(Array.isArray(src[c])?src[c]:[]).map(r=>({card:matchCard(r.card||r.cardId||r.name)||s(r.card||r.cardId||r.name),amount:n(r.amount)})).filter(r=>r.card&&r.amount>0);if(!out[c].length){const id=matchCard(raw[`card_${c}`]||(c==='general'?raw.card_general:''));if(id&&sp[c])out[c]=[{card:id,amount:sp[c]}]}}return out}
function progress(raw={}){const p=raw.statusProgress||raw.status_progress||{};return{delta:{mqd:n(p.delta?.mqd??raw.delta_mqd)},united:{pqp:n(p.united?.pqp??raw.united_pqp),pqf:n(p.united?.pqf??raw.united_pqf)},american:{loyaltyPoints:n(p.american?.loyaltyPoints??raw.american_loyalty_points)},southwest:{tqp:n(p.southwest?.tqp??raw.southwest_tqp),qualifyingFlights:n(p.southwest?.qualifyingFlights??raw.southwest_qualifying_flights)},hotel:{qualifyingNights:n(p.hotel?.qualifyingNights??raw.hotel_qualifying_nights??raw.hotel_nights),qualifyingStays:n(p.hotel?.qualifyingStays??raw.hotel_qualifying_stays??raw.hotel_stays),qualifyingSpend:n(p.hotel?.qualifyingSpend??raw.hotel_qualifying_spend??raw.hotel_spend)}}}
function remaining(raw={}){const f=raw.remainingYear||raw.remaining_year||raw.futureActivity||raw.future_activity,known=raw.remainingYearKnown===true||!!f,x=f||{},cs=x.cardSpend||x.statusSpend||{};return{known,cardSpend:Object.fromEntries(CATS.map(c=>[c,n(cs[c])])),delta:{mqd:n(x.delta?.mqd)},united:{pqp:n(x.united?.pqp),pqf:n(x.united?.pqf)},american:{loyaltyPoints:n(x.american?.loyaltyPoints)},southwest:{tqp:n(x.southwest?.tqp),qualifyingFlights:n(x.southwest?.qualifyingFlights)},hotel:{qualifyingNights:n(x.hotel?.qualifyingNights),qualifyingStays:n(x.hotel?.qualifyingStays),qualifyingSpend:n(x.hotel?.qualifyingSpend)}}}
function normalizeProfile(raw={}){const sp=spend(raw),cr=raw.currentCards||raw.primary_cards||raw.cards||[],cards=uniq((Array.isArray(cr)?cr:[cr]).map(v=>matchCard(v)||s(v)).filter(Boolean)),air=lc(raw.primaryAirline||raw.primary_airline_eco||raw.primary_airline),hot=lc(raw.primaryHotel||raw.primary_hotel||raw.hotel_program),as=n(raw.primaryAirlineShare??raw.primary_airline_share??raw.airline_concentration),hs=n(raw.primaryHotelShare??raw.primary_hotel_share??raw.hotel_concentration),c=raw.constraints||{},ar=raw.aspirations||raw.desiredOutcomes||raw.desired_outcomes||[],rf=raw.routeFit||raw.route_fit||{};return{spend:sp,totalSpend:sum(Object.values(sp)),currentCards:cards,currentRouting:routing(raw,sp),statusProgress:progress(raw),remainingYear:remaining(raw),cardTenure:raw.cardTenure||{},naturalBenefitValue:raw.naturalBenefitValue||{},hotelCardStackingAllowed:raw.hotelCardStackingAllowed===true,currencyUtility:{amex_mr:cl(n(raw.currencyUtility?.amex_mr??1),0,1),chase_ur:cl(n(raw.currencyUtility?.chase_ur??1),0,1),capital_one_miles:cl(n(raw.currencyUtility?.capital_one_miles??1),0,1),skymiles:cl(n(raw.currencyUtility?.skymiles??(air==='delta'?1:.45)),0,1),united_miles:cl(n(raw.currencyUtility?.united_miles??(air==='united'?1:.45)),0,1),aadvantage:cl(n(raw.currencyUtility?.aadvantage??(air==='american'?1:.45)),0,1),southwest_points:cl(n(raw.currencyUtility?.southwest_points??(air==='southwest'?1:.45)),0,1),hyatt_points:cl(n(raw.currencyUtility?.hyatt_points??(hot==='hyatt'?1:.45)),0,1),marriott_points:cl(n(raw.currencyUtility?.marriott_points??(hot==='marriott'?1:.45)),0,1),hilton_points:cl(n(raw.currencyUtility?.hilton_points??(hot==='hilton'?1:.45)),0,1)},travel:{annualOneWayFlights:n(raw.annualOneWayFlights??raw.one_way_flights??raw.flights_taken),bookingControl:lc(raw.bookingControl||raw.booking_control||'full'),typicalTripCashCost:n(raw.typicalTripCashCost??raw.typical_trip_cash_cost)},airline:{primary:air,share:cl((as>1?as/100:as)||(air?.70:0),0,1),reportedStatus:s(raw.currentAirlineStatus||raw.primary_airline_status||raw.airline_status),routeFit:Object.fromEntries(Object.entries(rf).map(([k,v])=>[lc(k),cl(n(v),0,1)])),statusUsefulOverride:typeof raw.airlineStatusUseful==='boolean'?raw.airlineStatusUseful:null},hotel:{primary:hot,share:cl((hs>1?hs/100:hs)||(hot?.60:0),0,1),reportedStatus:s(raw.currentHotelStatus||raw.primary_hotel_status||raw.hotel_status),premiumStayShare:cl(n(raw.premiumStayShare??raw.premium_stay_share)>1?n(raw.premiumStayShare??raw.premium_stay_share)/100:n(raw.premiumStayShare??raw.premium_stay_share),0,1)},aspirations:uniq((Array.isArray(ar)?ar:[ar]).map(lc)),constraints:{noNewCards:!!c.noNewCards,maxNewCards:c.maxNewCards==null?MODEL.maxNewCardsDefault:Math.max(0,n(c.maxNewCards)),noHotelConcentration:!!c.noHotelConcentration,prohibitedCards:uniq((c.prohibitedCards||[]).map(v=>matchCard(v)||s(v))),requiredCards:uniq((c.requiredCards||[]).map(v=>matchCard(v)||s(v)))},__normalizedV5:true}}
function tierIndex(program,tier){const rows=RULES.airlines[program]?.thresholds||RULES.hotels[program]?.thresholds||[];return rows.findIndex(r=>lc(r.tier)===lc(tier))}function maxTier(p,a,b){return tierIndex(p,a)>=tierIndex(p,b)?(a||''):(b||'')}
function airlineStatusUsefulness(p){if(p.airline.statusUsefulOverride!=null)return!!p.airline.statusUsefulOverride;return!!p.airline.primary&&p.airline.share>=MODEL.minAirlineShare&&p.travel.annualOneWayFlights>=MODEL.minFlightsForStatus&&p.travel.bookingControl!=='none'}
function hotelStatusUsefulness(p){return!!p.hotel.primary&&!p.constraints.noHotelConcentration&&p.hotel.share>=MODEL.minHotelShare&&p.statusProgress.hotel.qualifyingNights>=MODEL.minHotelNightsForStatus}
function rate(card,cat,amt){const b=card?.earn?.[cat]||0,cap=card?.caps?.[cat];return!cap||amt<=cap?b:((cap*b)+(amt-cap))/amt}function catValue(p,id,cat,amt,sc){const c=RULES.cards[id];return c&&amt>0?rate(c,cat,amt)*(VALUATIONS[sc][c.currency]||0)*(p.currencyUtility[c.currency]??.5):-Infinity}
function routeAnnual(p,portfolio,sc){const out={};for(const cat of CATS){const amt=p.spend[cat];if(!amt){out[cat]=[];continue}let id=null,v=-Infinity;for(const x of portfolio){const z=catValue(p,x,cat,amt,sc);if(z>v){v=z;id=x}}out[cat]=id?[{card:id,amount:amt}]:[]}return out}
function points(p,r,sc){const cur={};for(const cat of CATS)for(const x of r[cat]||[]){const c=RULES.cards[x.card];if(c)cur[c.currency]=(cur[c.currency]||0)+x.amount*rate(c,cat,x.amount)}let gross=0;for(const[k,v]of Object.entries(cur))gross+=v*(VALUATIONS[sc][k]||0)*(p.currencyUtility[k]??.5);return{pointsByCurrency:Object.fromEntries(Object.entries(cur).map(([k,v])=>[k,rnd(v)])),grossTravelValue:rnd(gross)}}
function visibleBenefits(portfolio){const out=[];for(const id of portfolio){const c=RULES.cards[id];if(!c)continue;for(const b of c.benefitTags||[])out.push({cardId:id,benefit:b});if(c.hotelStatus?.automaticTier)out.push({cardId:id,benefit:'automatic_hotel_status',detail:c.hotelStatus.automaticTier});if(c.airline&&c.status)out.push({cardId:id,benefit:'status_earning_mechanism',detail:c.airline})}return out}
function benefitRecommendationCredit(p,portfolio){const t=new Set(portfolio.flatMap(id=>RULES.cards[id]?.benefitTags||[]));return{lounge:t.has('lounge')&&p.travel.annualOneWayFlights>=6?1:0,premiumHotel:(t.has('premium_hotel_booking')||t.has('premium_hotel_benefits'))&&p.spend.hotel>0&&p.hotel.premiumStayShare>0?1:0,priorityAirport:t.has('priority_airport')&&p.travel.annualOneWayFlights>=6?1:0,upgradePriority:t.has('upgrade_priority')&&p.airline.primary==='delta'&&p.travel.annualOneWayFlights>=8?1:0}}
function economics(p,r,portfolio,sc){const q=points(p,r,sc),fees=sum(portfolio.map(id=>RULES.cards[id]?.annualFee||0)),benefits=sum(portfolio.map(id=>n(p.naturalBenefitValue[id])));return{...q,annualFees:fees,naturalBenefitValue:benefits,netEconomicValue:rnd(q.grossTravelValue+benefits-fees),unverifiedCards:portfolio.filter(id=>RULES.cards[id]?.verificationPending)}}
function airlineStrategy(p){return p.airline.primary?{type:'keep',airline:p.airline.primary,statusUseful:airlineStatusUsefulness(p),routeFitEstablished:p.airline.routeFit[p.airline.primary]!=null}:{type:'none',airline:'',statusUseful:false,routeFitEstablished:false}}
function hotelStrategy(p,credit){const a=hotelStatusUsefulness(p),b=credit.premiumHotel>0;return{type:a&&b?'mixed':a?'chain_loyalty_status':b?'premium_booking':'none',program:p.hotel.primary||''}}
function relevantCards(p){const f=['amex_gold','amex_platinum','chase_preferred','chase_reserve','venture','venture_x'],a={delta:['delta_platinum','delta_reserve'],united:['united_explorer','united_quest','united_club'],american:['aa_executive'],southwest:['southwest_priority']}[p.airline.primary]||[],h={hyatt:['hyatt_consumer'],marriott:['marriott_boundless','marriott_brilliant'],hilton:['hilton_no_fee','hilton_surpass','hilton_aspire']}[p.hotel.primary]||[];return uniq([...p.currentCards,...p.constraints.requiredCards,...f,...a,...h]).filter(id=>RULES.cards[id]&&!p.constraints.prohibitedCards.includes(id))}
function combos(a,max){const out=[];(function go(i,p){if(p.length<=max)out.push(p.slice());if(p.length===max)return;for(let j=i;j<a.length;j++){p.push(a[j]);go(j+1,p);p.pop()}})(0,[]);return out}
function badHotelStack(p,set){if(p.hotelCardStackingAllowed)return false;const m={};for(const id of set){const h=RULES.cards[id]?.hotel;if(h)(m[h]||=[]).push(id)}return Object.values(m).some(x=>x.length>1)}
function candidatePortfolios(p){const r=relevantCards(p),out=[];for(const set of combos(r,Math.min(MODEL.maxPortfolioCards,r.length))){if(!set.length&&p.totalSpend)continue;if(p.constraints.requiredCards.some(id=>!set.includes(id)))continue;const adds=set.filter(id=>!p.currentCards.includes(id)).length;if((p.constraints.noNewCards&&adds)||adds>p.constraints.maxNewCards||badHotelStack(p,set))continue;out.push(set)}if(!out.some(x=>JSON.stringify(x.slice().sort())===JSON.stringify(p.currentCards.slice().sort())))out.push(p.currentCards.slice());return out}
function remBase(p,annual){const out={};for(const cat of CATS){const rem=p.remainingYear.cardSpend[cat],tot=p.spend[cat];out[cat]=!rem||!tot?[]:(annual[cat]||[]).map(x=>({card:x.card,amount:rnd(rem*x.amount/tot)})).filter(x=>x.amount>0)}return out}function cardTotals(r){const o={};for(const c of CATS)for(const x of r[c]||[])o[x.card]=(o[x.card]||0)+x.amount;return o}
function curMetric(p,a){const x=p.statusProgress[a]||{};return a==='delta'?x.mqd:a==='united'?x.pqp:a==='american'?x.loyaltyPoints:a==='southwest'?x.tqp:0}function remMetric(p,a){const x=p.remainingYear[a]||{};return a==='delta'?x.mqd:a==='united'?x.pqp:a==='american'?x.loyaltyPoints:a==='southwest'?x.tqp:0}
function airTier(a,m,f){let t='';for(const x of RULES.airlines[a]?.thresholds||[])if(m>=x.amount)t=x.tier;if(a==='southwest')for(const x of RULES.airlines[a]?.flightThresholds||[])if(f>=x.flights)t=x.tier;return t}
function airProjection(p,a,remRouting,portfolio){let metric=curMetric(p,a)+remMetric(p,a),flights=a==='southwest'?p.statusProgress.southwest.qualifyingFlights+p.remainingYear.southwest.qualifyingFlights:0;const totals=cardTotals(remRouting);for(const id of portfolio){const c=RULES.cards[id],sp=totals[id]||0;if(!c||c.airline!==a||!c.status)continue;if(a==='delta'){if(!p.currentCards.includes(id))metric+=c.status.headstart||0;metric+=sp/c.status.spendDivisor}else if(a==='united'){metric+=Math.min(c.status.annualCap||Infinity,sp/c.status.spendDivisor);if(p.cardTenure[id]?.futureAnnualBonusEligible===true)metric+=c.status.annualBonus||0}else if(a==='american')metric+=sp*(c.status.lpPerEligiblePurchaseDollar||0);else if(a==='southwest')metric+=Math.floor(sp/c.status.spendBlock)*c.status.tqpPerBlock}return{metric:rnd(metric),qualifyingFlights:flights,tier:airTier(a,metric,flights)}}
function nextAirTarget(p,a,organic){const rules=RULES.airlines[a],ri=tierIndex(a,p.airline.reportedStatus),oi=tierIndex(a,organic.tier);if(ri>=0&&oi<ri)return{target:rules.thresholds[ri],type:'retain'};const target=rules.thresholds.find((x,i)=>i>Math.max(ri,oi));return target?{target,type:'upgrade'}:null}
function statusNeed(p,a,id,organic){const c=RULES.cards[id],plan=nextAirTarget(p,a,organic);if(!c?.status||!plan)return null;if(a==='southwest'){const ft=RULES.airlines[a].flightThresholds.find(x=>x.tier===plan.target.tier);if(ft&&organic.qualifyingFlights>=ft.flights)return{spend:0,...plan,achievedOrganically:true}}const gap=Math.max(0,plan.target.amount-organic.metric);if(!gap)return{spend:0,...plan,achievedOrganically:true};let sp=Infinity;if(a==='delta'||a==='united')sp=gap*c.status.spendDivisor;else if(a==='american')sp=gap/(c.status.lpPerEligiblePurchaseDollar||1);else if(a==='southwest')sp=Math.ceil(gap/c.status.tqpPerBlock)*c.status.spendBlock;return{spend:sp,...plan,achievedOrganically:false}}
function shift(p,r,target,need,sc){const out=cp(r),choices=[];for(const cat of CATS){const rows=out[cat]||[],avail=sum(rows.map(x=>x.amount));if(!avail)continue;const normal=rows[0]?.card,amt=p.spend[cat]||avail;choices.push({cat,avail,normal,loss:Math.max(0,catValue(p,normal,cat,amt,sc)-catValue(p,target,cat,amt,sc))})}choices.sort((a,b)=>a.loss-b.loss);let left=need,cost=0,moved=0;for(const q of choices){if(left<=0)break;const take=Math.min(q.avail,left),rows=out[q.cat];let x=take;for(const row of rows){if(row.card===target)continue;const z=Math.min(row.amount,x);row.amount=rnd(row.amount-z);x-=z;if(x<=0)break}const t=rows.find(r=>r.card===target);if(t)t.amount=rnd(t.amount+take);else rows.push({card:target,amount:rnd(take)});out[q.cat]=rows.filter(r=>r.amount>0);left-=take;moved+=take;cost+=take*q.loss}return left>0?null:{routing:out,shifted:rnd(moved),opportunityCost:rnd(cost)}}
function hotelProjection(p,portfolio,rr){const pr=p.hotel.primary;if(!pr)return{projectedTier:'',effectiveTier:p.hotel.reportedStatus||'',qualifyingNights:p.statusProgress.hotel.qualifyingNights};let nights=p.statusProgress.hotel.qualifyingNights+p.remainingYear.hotel.qualifyingNights,stays=p.statusProgress.hotel.qualifyingStays+p.remainingYear.hotel.qualifyingStays,spend=p.statusProgress.hotel.qualifyingSpend+p.remainingYear.hotel.qualifyingSpend,auto='',tot=cardTotals(rr);for(const id of portfolio){const c=RULES.cards[id],h=c?.hotelStatus;if(!h||c.hotel!==pr)continue;if(!p.currentCards.includes(id))nights+=h.annualNights||0;if(h.spendBlock&&h.nightsPerBlock)nights+=Math.floor((tot[id]||0)/h.spendBlock)*h.nightsPerBlock;if(h.automaticTier)auto=maxTier(pr,auto,h.automaticTier)}let earned='';if(pr==='hilton'){for(const x of RULES.hotels.hilton.thresholds)if(nights>=x.nights||stays>=x.stays||spend>=x.spend)earned=x.tier;const d=RULES.hotels.hilton.diamondReserve;if((nights>=d.nights||stays>=d.stays)&&spend>=d.spend)earned=d.tier}else for(const x of RULES.hotels[pr].thresholds)if(nights>=x.nights)earned=x.tier;const projectedTier=maxTier(pr,earned,auto);return{projectedTier,effectiveTier:maxTier(pr,p.hotel.reportedStatus,projectedTier),qualifyingNights:nights}}
function hotelNeed(p,portfolio,id,organic){const pr=p.hotel.primary,c=RULES.cards[id],h=c?.hotelStatus;if(!pr||!h||c.hotel!==pr||!hotelStatusUsefulness(p)||pr==='hilton'||!h.spendBlock)return null;const ri=tierIndex(pr,p.hotel.reportedStatus),oi=tierIndex(pr,organic.projectedTier),rules=RULES.hotels[pr].thresholds;let target,type;if(ri>=0&&oi<ri){target=rules[ri];type='retain'}else{target=rules.find((x,i)=>i>Math.max(ri,oi));type='upgrade'}if(!target)return null;const gap=Math.max(0,target.nights-organic.qualifyingNights);return gap?{spend:Math.ceil(gap/h.nightsPerBlock)*h.spendBlock,target,type}:{spend:0,target,type,achievedOrganically:true}}
function statusPlan(p,portfolio,annual,sc){const base=p.remainingYear.known?remBase(p,annual):Object.fromEntries(CATS.map(c=>[c,[]]));let rr=cp(base),airlineTarget=null,hotelTarget=null,cost=0,a=p.airline.primary;if(p.remainingYear.known&&airlineStatusUsefulness(p)&&a){const organic=airProjection(p,a,base,portfolio);let best=null;for(const id of portfolio.filter(id=>RULES.cards[id]?.airline===a)){const need=statusNeed(p,a,id,organic);if(!need||need.achievedOrganically||need.spend<=0)continue;const sh=shift(p,rr,id,need.spend,sc);if(!sh||sh.opportunityCost>MODEL.statusOpportunityCostLimit)continue;const pr=airProjection(p,a,sh.routing,portfolio);if(tierIndex(a,pr.tier)<tierIndex(a,need.target.tier))continue;if(!best||sh.opportunityCost<best.sh.opportunityCost)best={id,need,sh,pr}}if(best){rr=best.sh.routing;cost+=best.sh.opportunityCost;airlineTarget={airline:a,tier:best.need.target.tier,type:best.need.type,cardId:best.id,spendDirected:best.sh.shifted,projectedTier:best.pr.tier}}}if(p.remainingYear.known&&hotelStatusUsefulness(p)&&p.hotel.primary){const organic=hotelProjection(p,portfolio,base);let best=null;for(const id of portfolio.filter(id=>RULES.cards[id]?.hotel===p.hotel.primary&&RULES.cards[id]?.hotelStatus?.spendBlock)){const need=hotelNeed(p,portfolio,id,organic);if(!need||need.achievedOrganically||need.spend<=0)continue;const sh=shift(p,rr,id,need.spend,sc);if(!sh||sh.opportunityCost>MODEL.statusOpportunityCostLimit)continue;const pr=hotelProjection(p,portfolio,sh.routing);if(tierIndex(p.hotel.primary,pr.projectedTier)<tierIndex(p.hotel.primary,need.target.tier))continue;if(!best||sh.opportunityCost<best.sh.opportunityCost)best={id,need,sh,pr}}if(best){rr=best.sh.routing;cost+=best.sh.opportunityCost;hotelTarget={program:p.hotel.primary,tier:best.need.target.tier,type:best.need.type,cardId:best.id,spendDirected:best.sh.shifted,projectedTier:best.pr.projectedTier}}}return{routing:rr,airlineTarget,hotelTarget,opportunityCost:rnd(cost)}}
function unsupportedShare(p){let x=0;for(const c of CATS)for(const r of p.currentRouting[c]||[])if(!RULES.cards[r.card])x+=r.amount;return p.totalSpend?x/p.totalSpend:0}function quality(p,e){const issues=[],u=unsupportedShare(p);if(u>=MODEL.unsupportedMaterialSpendShare)issues.push({code:'unsupported_material_current_spend',severity:'blocking'});else if(u>0)issues.push({code:'unsupported_current_spend',severity:'high'});for(const id of e.unverifiedCards||[])issues.push({code:'rule_verification_pending',severity:'medium',detail:id});if(airlineStatusUsefulness(p)&&!p.remainingYear.known)issues.push({code:'remaining_year_activity_missing',severity:'medium'});return{issues,precisionSuppressed:issues.some(x=>x.severity==='blocking')}}
function actions(p,portfolio){const out=[];for(const id of p.currentCards){const r=RULES.cards[id];out.push({cardId:id,action:!r?'manual_review':portfolio.includes(id)?'keep':r.verificationPending?'manual_review':'remove_or_downgrade_after_review'})}for(const id of portfolio)if(!p.currentCards.includes(id))out.push({cardId:id,action:'add'});return out}function complexity(p,portfolio){const cur=uniq(portfolio.map(id=>RULES.cards[id]?.currency).filter(Boolean)),nw=portfolio.filter(id=>!p.currentCards.includes(id));return{cardCount:portfolio.length,newCardCount:nw.length,currencyCount:cur.length,burden:rnd(portfolio.length*MODEL.complexityPenaltyPerCard+cur.length*MODEL.complexityPenaltyPerCurrency+nw.length,2)}}
function record(p,portfolio,sc='base'){const annual=routeAnnual(p,portfolio,sc),eco=economics(p,annual,portfolio,sc),plan=statusPlan(p,portfolio,annual,sc),air=p.airline.primary&&p.remainingYear.known?airProjection(p,p.airline.primary,plan.routing,portfolio):{tier:''},hot=p.remainingYear.known?hotelProjection(p,portfolio,plan.routing):{projectedTier:'',effectiveTier:p.hotel.reportedStatus||''},credit=benefitRecommendationCredit(p,portfolio),effectiveAir=p.airline.primary?maxTier(p.airline.primary,p.airline.reportedStatus,air.tier):'',ri=p.airline.primary?tierIndex(p.airline.primary,p.airline.reportedStatus):-1,pi=p.airline.primary?tierIndex(p.airline.primary,air.tier):-1;const r={id:portfolio.slice().sort().join('+')||'no_cards',portfolio,annualRouting:annual,remainingYearRouting:plan.routing,economics:eco,strategy:{airlineStrategy:airlineStrategy(p),hotelStrategy:hotelStrategy(p,credit),airlineStatusTarget:plan.airlineTarget,hotelStatusTarget:plan.hotelTarget},outcomes:{travelCapacity:{annualTravelValue:eco.grossTravelValue,pointsByCurrency:eco.pointsByCurrency},flightQuality:{effectiveStatus:effectiveAir},airportExperience:{},hotelExperience:{effectiveStatus:hot.effectiveTier||''},reliability:{preservesCurrentAirlineStatus:ri<0||pi>=ri},cashEfficiency:{netEconomicValue:eco.netEconomicValue},complexity:complexity(p,portfolio)},visibleBenefits:visibleBenefits(portfolio),recommendationCredit:credit,actions:actions(p,portfolio)};r.quality=quality(p,eco);return r}
function currentRecord(p,sc='base'){const eco=economics(p,p.currentRouting,p.currentCards,sc),rem=p.remainingYear.known?remBase(p,p.currentRouting):Object.fromEntries(CATS.map(c=>[c,[]])),air=p.airline.primary&&p.remainingYear.known?airProjection(p,p.airline.primary,rem,p.currentCards):{tier:''},hot=p.remainingYear.known?hotelProjection(p,p.currentCards,rem):{effectiveTier:p.hotel.reportedStatus||''},credit=benefitRecommendationCredit(p,p.currentCards),ri=p.airline.primary?tierIndex(p.airline.primary,p.airline.reportedStatus):-1,pi=p.airline.primary?tierIndex(p.airline.primary,air.tier):-1,r={id:'current',portfolio:p.currentCards,annualRouting:cp(p.currentRouting),remainingYearRouting:rem,economics:eco,strategy:{airlineStrategy:airlineStrategy(p),hotelStrategy:hotelStrategy(p,credit),airlineStatusTarget:null,hotelStatusTarget:null},outcomes:{travelCapacity:{annualTravelValue:eco.grossTravelValue,pointsByCurrency:eco.pointsByCurrency},flightQuality:{effectiveStatus:p.airline.primary?maxTier(p.airline.primary,p.airline.reportedStatus,air.tier):''},hotelExperience:{effectiveStatus:hot.effectiveTier||''},reliability:{preservesCurrentAirlineStatus:ri<0||pi>=ri},cashEfficiency:{netEconomicValue:eco.netEconomicValue},complexity:complexity(p,p.currentCards)},visibleBenefits:visibleBenefits(p.currentCards),recommendationCredit:credit,actions:actions(p,p.currentCards)};r.quality=quality(p,eco);return r}
function compare(a,b){const imp=[],reg=[];if(a.outcomes.travelCapacity.annualTravelValue-b.outcomes.travelCapacity.annualTravelValue>=MODEL.materialTravelValue)imp.push('travelCapacity');if(b.outcomes.travelCapacity.annualTravelValue-a.outcomes.travelCapacity.annualTravelValue>=MODEL.materialTravelValue)reg.push('travelCapacity');if(a.economics.netEconomicValue-b.economics.netEconomicValue>=MODEL.materialCashImprovement)imp.push('cashEfficiency');if(b.economics.netEconomicValue-a.economics.netEconomicValue>=MODEL.materialCashImprovement)reg.push('cashEfficiency');const air=a.strategy.airlineStrategy.airline||b.strategy.airlineStrategy.airline;if(air){const ai=tierIndex(air,a.outcomes.flightQuality.effectiveStatus),bi=tierIndex(air,b.outcomes.flightQuality.effectiveStatus);if(ai>bi)imp.push('flightQuality');if(bi>ai)reg.push('flightQuality');if(a.outcomes.reliability.preservesCurrentAirlineStatus&&!b.outcomes.reliability.preservesCurrentAirlineStatus)imp.push('reliability');if(b.outcomes.reliability.preservesCurrentAirlineStatus&&!a.outcomes.reliability.preservesCurrentAirlineStatus)reg.push('reliability')}const h=a.strategy.hotelStrategy.program||b.strategy.hotelStrategy.program;if(h){const ai=tierIndex(h,a.outcomes.hotelExperience.effectiveStatus),bi=tierIndex(h,b.outcomes.hotelExperience.effectiveStatus);if(ai>bi)imp.push('hotelExperience');if(bi>ai)reg.push('hotelExperience')}if(a.recommendationCredit.premiumHotel>b.recommendationCredit.premiumHotel)imp.push('hotelExperience');if(b.recommendationCredit.premiumHotel>a.recommendationCredit.premiumHotel)reg.push('hotelExperience');const aa=a.recommendationCredit.lounge+a.recommendationCredit.priorityAirport+a.recommendationCredit.upgradePriority,bb=b.recommendationCredit.lounge+b.recommendationCredit.priorityAirport+b.recommendationCredit.upgradePriority;if(aa>bb)imp.push('airportExperience');if(bb>aa)reg.push('airportExperience');if(b.outcomes.complexity.burden-a.outcomes.complexity.burden>=2)imp.push('complexity');if(a.outcomes.complexity.burden-b.outcomes.complexity.burden>=2)reg.push('complexity');return{improvements:uniq(imp),regressions:uniq(reg)}}
function paretoSurvivors(rs){return rs.filter((r,i)=>!rs.some((o,j)=>i!==j&&compare(o,r).improvements.length&&compare(o,r).regressions.length===0))}function choose(p,rs,current){if(current.quality.precisionSuppressed)return current;const v=paretoSurvivors(rs).map(r=>({r,c:compare(r,current)})).filter(x=>x.c.improvements.length).filter(x=>{const non=x.c.improvements.some(k=>['flightQuality','airportExperience','hotelExperience','reliability'].includes(k));return non||x.r.economics.netEconomicValue>=current.economics.netEconomicValue}).filter(x=>x.c.regressions.filter(k=>k!=='complexity').length===0||x.c.improvements.length>x.c.regressions.filter(k=>k!=='complexity').length);v.sort((x,y)=>{const xi=x.c.improvements.filter(k=>k!=='complexity').length,yi=y.c.improvements.filter(k=>k!=='complexity').length;if(yi!==xi)return yi-xi;if(x.r.outcomes.complexity.burden!==y.r.outcomes.complexity.burden)return x.r.outcomes.complexity.burden-y.r.outcomes.complexity.burden;return y.r.economics.netEconomicValue-x.r.economics.netEconomicValue});return v[0]?.r||current}
function selectForScenario(p,sc){const current=currentRecord(p,sc),records=candidatePortfolios(p).map(x=>record(p,x,sc)),recommended=choose(p,records,current);return{current,records,recommended,pareto:paretoSurvivors(records)}}function presentationOrder(p){const base=['travelCapacity','flightQuality','airportExperience','hotelExperience','reliability','cashEfficiency','complexity'],m={'travel more':['travelCapacity','cashEfficiency'],'fly & airport better':['flightQuality','airportExperience','reliability'],'stay better':['hotelExperience'],'get more travel from what i already spend':['travelCapacity','cashEfficiency'],'show me everything':[]},first=[];for(const a of p.aspirations)for(const k of m[a]||[])if(!first.includes(k))first.push(k);return[...first,...base.filter(k=>!first.includes(k))]}
function recommendationFingerprint(x){const r=x.recommended||x;return JSON.stringify({portfolio:r.portfolio.slice().sort(),annualRouting:r.annualRouting,remainingYearRouting:r.remainingYearRouting,airlineStatusTarget:r.strategy.airlineStatusTarget,hotelStatusTarget:r.strategy.hotelStatusTarget})}
function analyze(raw){const p=raw?.__normalizedV5?raw:normalizeProfile(raw),c=selectForScenario(p,'conservative'),b=selectForScenario(p,'base'),u=selectForScenario(p,'upper'),fps=[c,b,u].map(x=>recommendationFingerprint(x.recommended));return{engineVersion:ENGINE_VERSION,rulesAsOf:RULES_AS_OF,profile:p,current:b.current,recommended:b.recommended,candidatesEvaluated:b.records.length,visibleBenefits:b.recommended.visibleBenefits,presentation:{aspirations:p.aspirations,order:presentationOrder(p)},sensitivity:{strategyStable:new Set(fps).size===1,recommendationIds:{conservative:c.recommended.id,base:b.recommended.id,upper:u.recommended.id}},integrity:{aspirationsUsedInRecommendationSelection:false,benefitVisibilitySeparatedFromRecommendationCredit:true,annualAndRemainingYearRoutingSeparated:true,reportedStatusAuthoritative:true,unsupportedMaterialSpendBlocksPrecision:b.current.quality.precisionSuppressed}}}
return Object.freeze({ENGINE_VERSION,RULES_AS_OF,RULES,VALUATIONS,MODEL,matchCard,normalizeProfile,airlineStatusUsefulness,hotelStatusUsefulness,visibleBenefits,benefitRecommendationCredit,candidatePortfolios,airlineProjection:airProjection,hotelProjection,strategyRecord:record,currentRecord,materialComparison:compare,paretoSurvivors,selectForScenario,analyze,recommendationFingerprint});
});
