import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { ENTITY_SOURCES, ALLOWED_CARD_IDS, ALLOWED_AIRLINE_IDS, ALLOWED_HOTEL_IDS } from "./sources.ts";

const ORIGINS=new Set(["https://quietpremium.com","https://www.quietpremium.com"]);\nconst PUBLIC_BROWSER_KEY="sb_publishable_BETG0zmWAEmPByBsKyEUzA_yPCOkh5F";
const MAX_ENTITIES=12,MAX_BYTES=2000000,TIMEOUT=9000,SCHEMA="qp-verified-facts-v1";
const uniq=(a:any[])=>[...new Set((a||[]).filter(Boolean))];
const amount=(v:any)=>{const n=Number(String(v??"").replace(/[$,%\s,]/g,""));return Number.isFinite(n)?n:null};
const cleanText=(h:string)=>String(h||"").replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/\s+/g," ").trim();
const has=(o:any,p:string)=>{let x=o;for(const k of p.split(".")){if(!x||!Object.prototype.hasOwnProperty.call(x,k))return false;x=x[k]}if(x==null)return false;if(Array.isArray(x))return x.length>0;if(typeof x==="object")return Object.keys(x).length>0;return true};
function j(body:any,status=200,origin=""){const h:any={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};if(origin&&ORIGINS.has(origin)){h["Access-Control-Allow-Origin"]=origin;h["Vary"]="Origin"}return new Response(JSON.stringify(body),{status,headers:h})}
function preflight(origin:string){if(!ORIGINS.has(origin))return new Response(null,{status:403});return new Response(null,{status:204,headers:{"Access-Control-Allow-Origin":origin,"Access-Control-Allow-Headers":"apikey, content-type, x-client-info","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Max-Age":"86400","Vary":"Origin"}})}
function keys(){const out:string[]=[PUBLIC_BROWSER_KEY];try{const x=JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")||"{}");for(const v of Object.values(x))if(typeof v==="string"&&v)out.push(v)}catch{}const a=Deno.env.get("SUPABASE_ANON_KEY");if(a)out.push(a);return new Set(out)}
function auth(req:Request){const k=req.headers.get("apikey")||"";return !!k&&keys().has(k)}
async function digest(s:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function get(url:string){const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT),retrievedAt=new Date().toISOString();try{const r=await fetch(url,{redirect:"follow",signal:c.signal,headers:{"Accept":"text/html,application/xhtml+xml,text/plain;q=0.9,*/*;q=0.5","Accept-Language":"en-US,en;q=0.8","User-Agent":"Mozilla/5.0 (compatible; QuietPremiumVerifier/1.0; +https://quietpremium.com)"}});const raw=(await r.text()).slice(0,MAX_BYTES);return{url,finalUrl:r.url||url,ok:r.ok,status:r.status,retrievedAt,bytesRead:raw.length,fingerprint:await digest(raw),text:cleanText(raw)}}catch(e){return{url,finalUrl:url,ok:false,status:0,retrievedAt,bytesRead:0,fingerprint:"",text:"",error:String((e as Error)?.message||e)}}finally{clearTimeout(t)}}
function first(text:string,res:RegExp[]){for(const r of res){const m=text.match(r);if(m)return m}return null}
function fee(t:string){if(/No Annual Fee/i.test(t))return 0;const m=first(t,[/Annual Fee\s*:?\s*\$\s*([\d,]+)/i,/\$\s*([\d,]+)\s+annual fee/i,/annual fee[^$]{0,80}\$\s*([\d,]+)/i,/then\s+\$\s*([\d,]+)[^.]{0,80}annual fee/i]);return m?amount(m[1]):null}
function rate(t:string,words:RegExp[]){for(const w of words){const q=w.source;const m=first(t,[new RegExp("(\\d+(?:\\.\\d+)?)\\s*[xX][^.]{0,100}"+q,"i"),new RegExp(q+"[^.]{0,100}(\\d+(?:\\.\\d+)?)\\s*[xX]","i")]);if(m)return Number(m[1])}return null}
function earn(t:string){const g=rate(t,[/all other (?:eligible )?purchases/i,/other eligible purchases/i,/every purchase/i]);if(!(g&&g>0))return null;const e:any={dining:g,grocery:g,online_grocery:g,gas_ev:g,online_retail:g,vacation_home:g,airfare:g,hotel:g,general:g};const set=(k:string,v:any)=>{if(v)e[k]=v};set("dining",rate(t,[/restaurants?/i,/dining/i]));const gr=rate(t,[/supermarkets?/i,/groceries/i]);if(gr){e.grocery=gr;e.online_grocery=gr}set("online_grocery",rate(t,[/online groceries/i,/online grocery/i]));set("gas_ev",rate(t,[/gas stations?/i,/EV charging/i]));set("online_retail",rate(t,[/online retail/i]));set("vacation_home",rate(t,[/vacation homes?/i,/Airbnb/i,/Vrbo/i]));set("airfare",rate(t,[/flights? booked directly/i,/Delta purchases?/i,/United purchases?/i,/American Airlines purchases?/i,/Southwest purchases?/i]));set("hotel",rate(t,[/Hyatt hotels?/i,/Hilton portfolio/i,/Marriott Bonvoy hotels?/i,/hotel stays?/i]));return e}
const TAGS:[string,RegExp][]=[["lounge",/Priority Pass|Centurion Lounge|United Club|Admirals Club|Sky Club|Capital One Lounge|airport lounge access/i],["premium_hotel_booking",/Fine Hotels \+ Resorts|Fine Hotels and Resorts|The Edit by Chase Travel|Premier Collection/i],["priority_airport",/priority (?:check-in|security|airport)|priority boarding/i],["upgrade_priority",/complimentary upgrade|upgrade priority/i],["checked_bag",/free checked bag|first bag free|second bag free/i],["companion_certificate_renewal",/companion certificate/i],["free_night_reward_annual",/annual free night|free night award every year|free night reward.*every year/i],["global_entry_tsa",/Global Entry|TSA PreCheck|NEXUS/i],["clear",/CLEAR\+? Credit/i],["hotel_status",/complimentary .* status|automatic .* status/i],["elite_night_credits",/elite night credits|qualifying night credits/i],["anniversary_miles",/anniversary (?:miles|points)/i],["travel_credit",/travel credit/i],["seat_benefits",/Preferred seats?|Extra Legroom seat/i],["boarding_benefits",/boarding benefit|priority boarding/i]];
function tags(t:string){return uniq(TAGS.filter(x=>x[1].test(t)).map(x=>x[0]))}
function near(t:string,re:RegExp){const m=re.exec(t);if(!m)return null;const s=t.slice(Math.max(0,m.index-180),Math.min(t.length,m.index+m[0].length+180));const a=[...s.matchAll(/\$\s*([0-9][0-9,]*)/g)].map(x=>amount(x[1])).filter(x=>x!=null) as number[];return a.length?Math.max(...a):null}
function credits(t:string){const o:any={};for(const [k,re]of [["dining_credit",/dining credit/i],["resy_credit",/Resy .*credit/i],["uber_cash",/Uber Cash/i],["rideshare_credit",/rideshare .*credit/i],["hotel_credit",/hotel .*credit/i],["capital_one_travel_credit",/Capital One Travel credit/i],["travel_credit",/travel credit/i],["airline_fee_credit",/airline fee credit/i],["flight_credit",/flight credit/i],["clear",/CLEAR\+? Credit/i],["digital_entertainment_credit",/digital entertainment.*credit/i],["resort_credit",/resort credit/i]] as [string,RegExp][]) {const v=near(t,re);if(v&&v<=10000)o[k]=v}return o}
function bonus(t:string){const m=first(t,[/(\d{1,3}(?:,\d{3})+)\s+anniversary\s+(?:miles|points)/i,/anniversary[^0-9]{0,80}(\d{1,3}(?:,\d{3})+)\s+(?:miles|points)/i]);return m?amount(m[1]):0}
function hotelStatus(t:string,id:string){const o:any={};for(const [tier,re]of [["Diamond",/complimentary (?:Hilton Honors )?Diamond status/i],["Gold",/complimentary (?:Hilton Honors )?Gold status/i],["Silver",/complimentary (?:Hilton Honors )?Silver status/i],["Platinum Elite",/complimentary (?:Marriott Bonvoy )?Platinum Elite status/i],["Gold Elite",/complimentary (?:Marriott Bonvoy )?Gold Elite status/i],["Silver Elite",/(?:automatic|complimentary) (?:Marriott Bonvoy )?Silver Elite status/i],["Discoverist",/(?:complimentary|receive) (?:World of Hyatt )?Discoverist status/i]] as [string,RegExp][])if(re.test(t)){o.automaticTier=tier;break}const n=first(t,[/(?:receive|get)\s+(\d+)\s+(?:elite |tier )?qualifying night credits?/i,/(\d+)\s+Elite Night Credits/i]);if(n)o.annualNights=Number(n[1]);const b=first(t,[/(\d+)\s+qualifying night credits?[^.]{0,100}every time you spend\s+\$\s*([\d,]+)/i]);if(b){o.nightsPerBlock=Number(b[1]);o.spendBlock=amount(b[2])}const st=first(t,[/spend\s+\$\s*([\d,]+)[^.]{0,180}(?:earn|upgrade to|receive)[^.]{0,80}(Silver|Gold|Diamond|Platinum)(?: Elite)? status/i]);if(st)o.spendTier={amount:amount(st[1]),tier:st[2]+(id.startsWith("marriott_")&&!/Elite/i.test(st[2])?" Elite":"")};return o}
function status(t:string,id:string){const o:any={};if(id.startsWith("delta_")){const h=first(t,[/MQD Headstart[^$0-9]{0,180}\$?\s*([\d,]+)\s*MQD/i]);if(h)o.headstart=amount(h[1]);const d=first(t,[/1\s+MQD[^.]{0,100}(?:for every|per)\s+\$\s*(\d+)/i]);if(d)o.spendDivisor=Number(d[1])}else if(id.startsWith("united_")){const d=first(t,[/1\s+PQP[^.]{0,100}(?:for every|per)\s+\$\s*(\d+)/i]);if(d)o.spendDivisor=Number(d[1]);const c=first(t,[/up to\s+([\d,]+)\s+PQP/i]);if(c)o.annualCap=amount(c[1]);const b=first(t,[/([\d,]+)\s+Card Bonus PQP/i]);if(b){o.annualBonus=amount(b[1]);o.bonusRequiresPriorYearOpen=true}}else if(id==="southwest_priority"){const q=first(t,[/([\d,]+)\s+TQPs?\s+for each\s+\$\s*([\d,]+)/i]);if(q){o.tqpPerBlock=amount(q[1]);o.spendBlock=amount(q[2])}}else if(id==="aa_executive"){if(/1\s+Loyalty Point[^.]{0,100}\$?1/i.test(t))o.lpPerEligiblePurchaseDollar=1}return o}
function cardFacts(id:string,t:string){const recurring=credits(t),derivedTags=uniq([...tags(t),...Object.keys(recurring),...( /trip cancellation|trip interruption|auto rental collision|travel insurance/i.test(t)?["travel_protections"]:[]),...( /Lifestyle Collection/i.test(t)?["lifestyle_collection"]:[]),...( /The Edit by Chase Travel/i.test(t)?["premium_hotel_booking"]:[])]);const f:any={bookingEarn:{},caps:{},capGroups:{},groupCaps:{},postCapEarn:{},benefitTags:derivedTags,recurringCredits:recurring,multiYearCredits:{},annualBonusPoints:bonus(t),hotelStatus:hotelStatus(t,id),hotelStatusByProgram:{},status:status(t,id),transferRules:{},verified:true};const unresolved:string[]=[];const af=fee(t);if(af==null)unresolved.push("annualFee");else f.annualFee=af;const er=earn(t);if(!er)unresolved.push("earn");else f.earn=er;if(id.startsWith("chase_")&&/World of Hyatt[^.]{0,180}(?:1\s*:\s*1|1 to 1)|(?:1\s*:\s*1|1 to 1)[^.]{0,180}World of Hyatt/i.test(t))f.transferRules={hyatt:{defaultRatio:1}};if(/Marriott Bonvoy[^.]{0,100}Gold Elite/i.test(t))f.hotelStatusByProgram.marriott="Gold Elite";if(/Hilton Honors[^.]{0,100}Gold/i.test(t))f.hotelStatusByProgram.hilton="Gold";return{facts:f,unresolved}}
function programFacts(kind:string,id:string,t:string){const f:any={};
if(kind==="airlines"&&id==="delta"){
  f.thresholds=[];
  const defs:[string,RegExp[]][]=[
    ["Silver Medallion",[/\$?\s*([\d,]+)\s+for Silver/i,/Silver[^$0-9]{0,60}\$?\s*([\d,]+)\s*MQD/i]],
    ["Gold Medallion",[/\$?\s*([\d,]+)\s+for Gold/i,/Gold[^$0-9]{0,60}\$?\s*([\d,]+)\s*MQD/i]],
    ["Platinum Medallion",[/\$?\s*([\d,]+)\s+for Platinum/i,/Platinum[^$0-9]{0,60}\$?\s*([\d,]+)\s*MQD/i]],
    ["Diamond Medallion",[/\$?\s*([\d,]+)\s+for Diamond/i,/Diamond[^$0-9]{0,60}\$?\s*([\d,]+)\s*MQD/i]]
  ];
  for(const[tier,res]of defs){const m=first(t,res);if(m)f.thresholds.push({tier,amount:amount(m[1])})}
  if(f.thresholds.length<4){const anchor=t.search(/MQD Thresholds for Status/i),slice=anchor>=0?t.slice(anchor,anchor+1600):t,vals=[...slice.matchAll(/\$\s*([\d,]+)\s*MQDs?/gi)].map(x=>amount(x[1])).filter((x:any)=>x!=null);if(vals.length>=4)f.thresholds=[["Silver Medallion",vals[0]],["Gold Medallion",vals[1]],["Platinum Medallion",vals[2]],["Diamond Medallion",vals[3]]].map(([tier,a])=>({tier,amount:a}))}
}else if(kind==="airlines"&&id==="american"){
  f.thresholds=[];
  if(/40,000\s+Loyalty Points/i.test(t))f.thresholds.push({tier:"Gold",amount:40000});
  if(/75,000\s+Loyalty Points/i.test(t))f.thresholds.push({tier:"Platinum",amount:75000});
  if(/125,000\s+Loyalty Points/i.test(t))f.thresholds.push({tier:"Platinum Pro",amount:125000});
  if(/200,000\s+Loyalty Points/i.test(t))f.thresholds.push({tier:"Executive Platinum",amount:200000});
}else if(kind==="airlines"&&id==="southwest"){
  f.thresholds=[];f.flightThresholds=[];
  for(const[tier,re]of [["A-List",/A-List[^.]{0,180}(\d+)\s+qualifying one-way flights?[^.]{0,120}([\d,]+)\s+tier qualifying points/i],["A-List Preferred",/A-List Preferred[^.]{0,180}(\d+)\s+qualifying one-way flights?[^.]{0,120}([\d,]+)\s+tier qualifying points/i]] as [string,RegExp][]) {const m=t.match(re);if(m){f.thresholds.push({tier,amount:amount(m[2])});f.flightThresholds.push({tier,flights:amount(m[1])})}}
}else if(kind==="airlines"&&id==="united"){
  f.thresholds=[];
  const defs:[string,RegExp[]][]=[
    ["Premier Silver",[/Silver[^.]{0,220}([\d,]+)\s+PQP\s*\+\s*([\d,]+)\s+PQF[^.]{0,160}or[^.]{0,80}([\d,]+)\s+PQP/i]],
    ["Premier Gold",[/Gold[^.]{0,220}([\d,]+)\s+PQP\s*\+\s*([\d,]+)\s+PQF[^.]{0,160}or[^.]{0,80}([\d,]+)\s+PQP/i]],
    ["Premier Platinum",[/Platinum[^.]{0,220}([\d,]+)\s+PQP\s*\+\s*([\d,]+)\s+PQF[^.]{0,160}or[^.]{0,80}([\d,]+)\s+PQP/i]],
    ["Premier 1K",[/1K[^.]{0,220}([\d,]+)\s+PQP\s*\+\s*([\d,]+)\s+PQF[^.]{0,160}or[^.]{0,80}([\d,]+)\s+PQP/i]]
  ];
  for(const[tier,res]of defs){const m=first(t,res);if(m)f.thresholds.push({tier,pqfPqp:amount(m[1]),pqf:amount(m[2]),amount:amount(m[3])})}
  const seg=first(t,[/minimum of\s+(\d+)\s+(?:paid )?(?:flight )?segments?/i,/(\d+)\s+(?:paid )?(?:flight )?segments?[^.]{0,100}(?:United|United Express)/i]);if(seg)f.minimumUnitedSegments=amount(seg[1]);
}else if(kind==="hotels"){
  f.thresholds=[];
  const defs:any=id==="marriott"?[["Silver Elite",/Silver Elite\s+(\d+)\s+nights per year/i],["Gold Elite",/Gold Elite\s+(\d+)\s+nights per year/i],["Platinum Elite",/Platinum Elite\s+(\d+)\s+nights per year/i],["Titanium Elite",/Titanium Elite\s+(\d+)\s+nights per year/i]]:id==="hyatt"?[["Discoverist",/Discoverist[^.]{0,160}(\d+)\s+(?:qualifying )?nights/i],["Explorist",/Explorist[^.]{0,160}(\d+)\s+(?:qualifying )?nights/i],["Globalist",/Globalist[^.]{0,160}(\d+)\s+(?:qualifying )?nights/i]]:[];
  for(const[tier,re]of defs){const m=t.match(re);if(m)f.thresholds.push({tier,nights:amount(m[1])})}
  if(id==="hilton"){for(const[tier,re]of [["Silver",/Silver:\s*(\d+)\s+nights,\s*(\d+)\s+stays,\s*or\s*\$\s*([\d,]+)/i],["Gold",/Gold:\s*(\d+)\s+nights,\s*(\d+)\s+stays,\s*or\s*\$\s*([\d,]+)/i],["Diamond",/Diamond:\s*(\d+)\s+nights,\s*(\d+)\s+stays,\s*or\s*\$\s*([\d,]+)/i]] as [string,RegExp][]) {const m=t.match(re);if(m)f.thresholds.push({tier,nights:amount(m[1]),stays:amount(m[2]),spend:amount(m[3])})}const dr=first(t,[/Diamond Reserve:\s*(\d+)\s+nights[^$]{0,100}\$\s*([\d,]+)[^.]{0,100}or\s*(\d+)\s+stays[^$]{0,100}\$\s*([\d,]+)/i,/(\d+)\s+nights\s+AND\s+\$\s*([\d,]+)[^.]{0,100}(\d+)\s+stays\s+AND\s+\$\s*([\d,]+)/i]);if(dr)f.diamondReserve={tier:"Diamond Reserve",nights:amount(dr[1]),stays:amount(dr[3]),spend:amount(dr[2])}}
}return f}
function materialUnmapped(t:string,f:any){const out:string[]=[];const rules:[string,RegExp,boolean][]=[["statement_credit",/statement credit/i,Object.keys(f.recurringCredits||{}).length>0||Object.keys(f.multiYearCredits||{}).length>0],["lounge",/Priority Pass|Centurion Lounge|United Club|Admirals Club|Sky Club|Capital One Lounge/i,(f.benefitTags||[]).includes("lounge")],["free_night",/Free Night (?:Reward|Award)|annual free night/i,(f.benefitTags||[]).some((x:string)=>x.includes("free_night"))||!!f.hotelStatus?.spendRewards],["companion",/companion certificate/i,(f.benefitTags||[]).includes("companion_certificate_renewal")],["hotel_status",/complimentary .* status|automatic .* status/i,Object.keys(f.hotelStatus||{}).length>0||Object.keys(f.hotelStatusByProgram||{}).length>0]];for(const[n,re,mapped]of rules)if(re.test(t)&&!mapped)out.push(n);return out}
function complete(spec:any,f:any,t:string,kind:string){const missing=(spec.required||[]).filter((p:string)=>!has(f,p)),unmapped=kind==="cards"?materialUnmapped(t,f):[];return{complete:missing.length===0&&unmapped.length===0,missing,unmapped}}
async function verify(kind:"cards"|"airlines"|"hotels",id:string){const spec=(ENTITY_SOURCES as any)[kind][id],rows=await Promise.all(spec.urls.map(get)),ok=rows.filter((x:any)=>x.ok&&x.text),text=ok.map((x:any)=>x.text).join(" "),ext=kind==="cards"?cardFacts(id,text):{facts:programFacts(kind,id,text),unresolved:[]},q=complete(spec,ext.facts,text,kind),status=ok.length===0?"unavailable":q.complete?"verified":"partial";return{verificationStatus:status,complete:q.complete,verifiedAt:new Date().toISOString(),sources:rows.map(({text,...m}:any)=>m),facts:ext.facts,unresolved:uniq([...(ext.unresolved||[]),...q.missing,...q.unmapped])}}
function ids(body:any,key:string,allowed:string[]){const a=uniq((Array.isArray(body?.[key])?body[key]:[]).map((x:any)=>String(x||"").trim().toLowerCase()));return{ids:a,invalid:a.filter((x:any)=>!allowed.includes(x))}}
Deno.serve(async(req:Request)=>{const origin=req.headers.get("origin")||"";if(req.method==="OPTIONS")return preflight(origin);if(req.method!=="POST")return j({error:"method_not_allowed"},405,origin);if(origin&&!ORIGINS.has(origin))return j({error:"origin_not_allowed"},403,origin);if(!auth(req))return j({error:"unauthorized"},401,origin);let body:any;try{body=await req.json()}catch{return j({error:"invalid_json"},400,origin)}const c=ids(body,"cards",ALLOWED_CARD_IDS),a=ids(body,"airlines",ALLOWED_AIRLINE_IDS),h=ids(body,"hotels",ALLOWED_HOTEL_IDS),invalid=[...c.invalid,...a.invalid,...h.invalid];if(invalid.length)return j({error:"unsupported_entity",invalid},400,origin);const total=c.ids.length+a.ids.length+h.ids.length;if(!total)return j({error:"no_entities_requested"},400,origin);if(total>MAX_ENTITIES)return j({error:"too_many_entities",max:MAX_ENTITIES,requested:total},400,origin);const cards:any={},airlines:any={},hotels:any={},jobs:any[]=[...c.ids.map((x:any)=>["cards",x]),...a.ids.map((x:any)=>["airlines",x]),...h.ids.map((x:any)=>["hotels",x])];for(let i=0;i<jobs.length;i+=4){const done=await Promise.all(jobs.slice(i,i+4).map((x:any)=>verify(x[0],x[1]).then(record=>({kind:x[0],id:x[1],record}))));for(const x of done)({cards,airlines,hotels} as any)[x.kind][x.id]=x.record}const records:any[]=[...Object.values(cards),...Object.values(airlines),...Object.values(hotels)],fingerprints=records.flatMap(x=>x.sources||[]).map(x=>x.fingerprint).filter(Boolean).sort().join("|"),verifiedAt=new Date().toISOString(),snapshotId="qpf_"+verifiedAt.replace(/\D/g,"").slice(0,14)+"_"+(await digest(fingerprints||verifiedAt)).slice(0,12),sources=records.flatMap(x=>x.sources||[]).map(x=>({url:x.finalUrl||x.url,status:x.status,retrievedAt:x.retrievedAt,fingerprint:x.fingerprint}));return j({schema:SCHEMA,snapshotId,verifiedAt,sources,cards,airlines,hotels},200,origin)});
