export const ENTITY_SOURCES = Object.freeze({
  cards: Object.freeze({
    amex_green: { urls: ['https://www.americanexpress.com/en-us/account/get-started/green/set-up-and-payments','https://www.americanexpress.com/us/credit-cards/card/green/','https://www.americanexpress.com/en-us/travel/benefits/clear/'], required: ['annualFee','earn','benefitTags','recurringCredits.clear'] },
    amex_gold: { urls: ['https://www.americanexpress.com/en-us/credit-cards/credit-intel/gold-card-annual-fee/index.shtml','https://www.americanexpress.com/en-us/account/get-started/gold/earn-rewards','https://www.americanexpress.com/en-us/account/get-started/gold/explore-benefits'], required: ['annualFee','earn','bookingEarn','caps','groupCaps','postCapEarn','benefitTags','recurringCredits'] },
    amex_platinum: { urls: ['https://www.americanexpress.com/en-us/credit-cards/credit-intel/amex-platinum-marriott-benefits/','https://www.americanexpress.com/en-us/travel/offers/hotels/hilton-luxury','https://www.americanexpress.com/en-us/credit-cards/credit-intel/american-express-platinum-shopping-benefits/','https://www.americanexpress.com/en-us/credit-cards/credit-intel/platinum-travel-benefits/','https://www.americanexpress.com/en-us/travel/cardmember-travel-benefits/','https://www.americanexpress.com/en-us/benefits/travel/expedite-your-travel/','https://www.americanexpress.com/en-us/credit-cards/credit-intel/platinum-fee/'], required: ['annualFee','earn','bookingEarn','caps.airfare','benefitTags','recurringCredits.hotel_credit','recurringCredits.resy_credit','recurringCredits.digital_entertainment_credit','recurringCredits.lululemon_credit','recurringCredits.uber_one_credit','recurringCredits.oura_credit','recurringCredits.uber_cash','recurringCredits.airline_fee_credit','recurringCredits.walmart_plus_credit','recurringCredits.equinox_credit','recurringCredits.clear','multiYearCredits.trusted_traveler','hotelStatusByProgram.marriott','hotelStatusByProgram.hilton'] },
    chase_preferred: { urls: ['https://creditcards.chase.com/rewards-credit-cards/sapphire/preferred','https://www.chase.com/sapphire-cards/personal/preferred'], required: ['annualFee','earn','bookingEarn.airfare.chase_travel','bookingEarn.hotel.chase_travel','bookingEarn.vacation_home.chase_travel','benefitTags','recurringCredits.chase_travel_hotel_credit','multiYearCredits.trusted_traveler','transferRules.hyatt.defaultRatio','temporaryBenefits'] },
    chase_freedom_unlimited: { urls: ['https://creditcards.chase.com/cash-back-credit-cards/freedom/unlimited','https://asset.chase.com/content/dam/card/rulesregulations/en/RPA0509_Web.pdf','https://www.chase.com/personal/credit-cards/education/basics/how-to-transfer-chase-ultimate-rewards-points','https://www.chase.com/personal/credit-cards/education/rewards-benefits/how-to-combine-chase-credit-card-points-in-household'], required: ['annualFee','earn','bookingEarn.airfare.chase_travel','bookingEarn.hotel.chase_travel','bookingEarn.vacation_home.chase_travel','benefitTags','transferAccess.canPool','transferAccess.directPartnerTransfer'] },
    chase_freedom_flex: { urls: ['https://creditcards.chase.com/cash-back-credit-cards/freedom/flex','https://www.chase.com/personal/credit-cards/education/basics/how-to-transfer-chase-ultimate-rewards-points','https://www.chase.com/personal/credit-cards/education/rewards-benefits/how-to-combine-chase-credit-card-points-in-household'], required: ['annualFee','earn','bookingEarn.airfare.chase_travel','bookingEarn.hotel.chase_travel','bookingEarn.vacation_home.chase_travel','benefitTags','rotatingBonus.rate','rotatingBonus.quarterlyCap','transferAccess.canPool','transferAccess.directPartnerTransfer'] },
    chase_freedom_rise: { urls: ['https://creditcards.chase.com/cash-back-credit-cards/freedom/rise','https://www.chase.com/personal/credit-cards/education/basics/how-to-transfer-chase-ultimate-rewards-points','https://www.chase.com/personal/credit-cards/education/rewards-benefits/how-to-combine-chase-credit-card-points-in-household'], required: ['annualFee','earn','transferAccess.canPool','transferAccess.directPartnerTransfer'] },
    chase_reserve: { urls: ['https://creditcards.chase.com/rewards-credit-cards/sapphire/reserve','https://www.chase.com/sapphire-cards/personal/reserve'], required: ['annualFee','earn','bookingEarn.airfare.chase_travel','bookingEarn.hotel.chase_travel','bookingEarn.vacation_home.chase_travel','benefitTags','recurringCredits.travel_credit','recurringCredits.edit_credit','recurringCredits.dining_credit','multiYearCredits.trusted_traveler','spendRewards','qualitativeSpendRewards','temporaryBenefits'] },
    venture_one: { urls: ['https://www.capitalone.com/credit-cards/ventureone/','https://www.capitalone.com/credit-cards/travel-and-miles/','https://www.capitalone.com/learn-grow/money-management/venture-vs-ventureone/'], required: ['annualFee','earn','bookingEarn.hotel.capital_one_travel','bookingEarn.vacation_home.capital_one_travel'] },
    venture: { urls: ['https://www.capitalone.com/credit-cards/venture/','https://www.capitalone.com/help-center/credit-cards/tsa-precheck-global-entry-benefits/'], required: ['annualFee','earn','bookingEarn.hotel.capital_one_travel','bookingEarn.vacation_home.capital_one_travel','benefitTags','multiYearCredits.trusted_traveler'] },
    venture_x: { urls: ['https://www.capitalone.com/credit-cards/venture-x/','https://www.capitalone.com/help-center/credit-cards/tsa-precheck-global-entry-benefits/','https://www.capitalone.com/credit-cards/travel-and-miles/','https://www.capitalone.com/learn-grow/more-than-money/all-about-venture-x/'], required: ['annualFee','earn','bookingEarn.airfare.capital_one_travel','bookingEarn.hotel.capital_one_travel','bookingEarn.vacation_home.capital_one_travel','benefitTags','recurringCredits.capital_one_travel_credit','annualBonusPoints','multiYearCredits.trusted_traveler'] },
    delta_blue: { urls: ['https://www.americanexpress.com/us/credit-cards/card/delta-skymiles-blue-american-express-card/'], required: ['annualFee','earn','benefitTags'] },
    delta_gold: { urls: ['https://www.americanexpress.com/us/credit-cards/card/delta-skymiles-gold-american-express-card/','https://global.americanexpress.com/card-benefits/view-all/delta-gold'], required: ['annualFee','earn','benefitTags','recurringCredits.rideshare_credit','recurringCredits.delta_stays_credit','spendRewards'] },
    delta_platinum: { urls: ['https://www.americanexpress.com/us/credit-cards/card/delta-skymiles-platinum-american-express-card/','https://global.americanexpress.com/card-benefits/view-all/delta-platinum','https://www.delta.com/us/en/booking-information/companion-certificates'], required: ['annualFee','earn','benefitTags','recurringCredits.rideshare_credit','recurringCredits.resy_credit','recurringCredits.delta_stays_credit','multiYearCredits.trusted_traveler','status.headstart','status.spendDivisor','companionCertificate.usesPerYear','companionCertificate.tripType','companionCertificate.cabin','companionCertificate.domesticEligible','companionCertificate.domesticMaxTaxesFees','companionCertificate.renewalRequired'] },
    delta_reserve: { urls: ['https://www.americanexpress.com/us/credit-cards/card/delta-skymiles-reserve-american-express-card/','https://global.americanexpress.com/card-benefits/view-all/delta-reserve','https://www.americanexpress.com/en-us/credit-cards/credit-intel/delta-reserve-card-benefits/','https://www.delta.com/us/en/booking-information/companion-certificates'], required: ['annualFee','earn','benefitTags','recurringCredits.rideshare_credit','recurringCredits.resy_credit','recurringCredits.delta_stays_credit','multiYearCredits.trusted_traveler','status.headstart','status.spendDivisor','companionCertificate.usesPerYear','companionCertificate.tripType','companionCertificate.cabin','companionCertificate.domesticEligible','companionCertificate.domesticMaxTaxesFees','companionCertificate.renewalRequired'] },
    united_gateway: { urls: ['https://creditcards.chase.com/travel-credit-cards/united/united-gateway'], required: ['annualFee','earn','benefitTags','spendRewards'] },
    united_explorer: { urls: ['https://creditcards.chase.com/travel-credit-cards/united/united-explorer','https://www.chase.com/personal/credit-cards/united/united-explorer-card'], required: ['annualFee','earn','benefitTags','recurringCredits.united_hotels_credit','recurringCredits.rideshare_credit','recurringCredits.avis_budget_credit','recurringCredits.instacart_credit','recurringCredits.jsx_credit','multiYearCredits.trusted_traveler','status.spendDivisor','status.annualCap','spendRewards'] },
    united_quest: { urls: ['https://creditcards.chase.com/travel-credit-cards/united/united-quest','https://www.chase.com/personal/credit-cards/united/united-quest-card'], required: ['bookingEarn.hotel.renowned_prepaid','annualFee','earn','benefitTags','recurringCredits.united_travel_credit','recurringCredits.renowned_hotels_credit','recurringCredits.rideshare_credit','recurringCredits.avis_budget_credit','recurringCredits.instacart_credit','recurringCredits.jsx_credit','multiYearCredits.trusted_traveler','status.spendDivisor','status.annualCap','status.annualBonus','annualPointCertificates','spendRewards'] },
    united_club: { urls: ['https://creditcards.chase.com/travel-credit-cards/united/club-infinite','https://www.chase.com/personal/credit-cards/united/united-visa-infinite-card'], required: ['bookingEarn.hotel.renowned_prepaid','annualFee','earn','benefitTags','recurringCredits.renowned_hotels_credit','recurringCredits.rideshare_credit','recurringCredits.avis_budget_credit','recurringCredits.instacart_credit','recurringCredits.jsx_credit','multiYearCredits.trusted_traveler','status.spendDivisor','status.annualCap','status.annualBonus','spendRewards'] },
    aa_mileup: { urls: ['https://www.citi.com/credit-cards/aadvantage-mile-up-credit-card'], required: ['annualFee','earn','benefitTags','status.lpPerEligiblePurchaseDollar'] },
    aa_platinum_select: { urls: ['https://www.citi.com/credit-cards/citi-aadvantage-platinum-select-world-elite-mastercard','https://www.citi.com/credit-cards/credit-card-miles/aadvantage-platinum-select-benefits'], required: ['annualFee','earn','benefitTags','status.lpPerEligiblePurchaseDollar','spendRewards'] },
    aa_executive: { urls: ['https://www.citi.com/credit-cards/citi-aadvantage-executive-world-legend-mastercard','https://www.aa.com/web/i18n/travel-info/clubs/admirals-club-membership.html'], required: ['annualFee','earn','bookingEarn.hotel.aadvantage_hotels','benefitTags','recurringCredits.aa_vacations_credit','recurringCredits.lyft_credit','recurringCredits.inflight_admirals_credit','recurringCredits.avis_budget_credit','multiYearCredits.trusted_traveler','status.lpPerEligiblePurchaseDollar','statusMilestoneRewards'] },
    aa_globe: { urls: ['https://www.citi.com/credit-cards/citi-aadvantage-globe-mastercard','https://creditcards.aa.com/credit-cards/globeprescreen/','https://creditcards.aa.com/credit-cards/citi-globe-card-american-airlines-direct/'], required: ['annualFee','earn','bookingEarn.hotel.aadvantage_hotels','benefitTags','recurringCredits.turo_credit','recurringCredits.inflight_credit','recurringCredits.splurge_credit','multiYearCredits.trusted_traveler','status.lpPerEligiblePurchaseDollar','status.flightStreakBlock','status.flightStreakBonus','status.flightStreakAnnualCap','companionCertificate.ticketingFee','companionCertificate.geography','companionCertificate.cabin','companionCertificate.tripType','companionCertificate.usesPerYear','companionCertificate.domesticEligible','companionCertificate.renewalRequired'] },
    southwest_plus: { urls: ['https://creditcards.chase.com/travel-credit-cards/southwest/plus'], required: ['annualFee','earn','benefitTags','annualBonusPoints','status.companionPassBoost'] },
    southwest_premier: { urls: ['https://creditcards.chase.com/travel-credit-cards/southwest/premier'], required: ['annualFee','earn','benefitTags','annualBonusPoints','status.spendBlock','status.tqpPerBlock','status.companionPassBoost'] },
    southwest_priority: { urls: ['https://creditcards.chase.com/travel-credit-cards/southwest/priority','https://www.southwest.com/rapid-rewards/tiers/a-list/'], required: ['annualFee','earn','benefitTags','annualBonusPoints','status.spendBlock','status.tqpPerBlock','status.companionPassBoost'] },
    hyatt_consumer: { urls: ['https://creditcards.chase.com/travel-credit-cards/world-of-hyatt-credit-card','https://www.chase.com/personal/credit-cards/hyatt/world-hyatt/earn-points','https://www.chase.com/personal/credit-cards/hyatt/world-hyatt/earn-maintain'], required: ['annualFee','earn.hotel','earn.dining','earn.airfare','earn.transit','earn.general','benefitTags','annualCategoryCertificates','qualitativeSpendRewards','hotelStatus.automaticTier','hotelStatus.annualNights','hotelStatus.spendBlock','hotelStatus.nightsPerBlock'] },
    marriott_bold: { urls: ['https://creditcards.chase.com/travel-credit-cards/marriott-bonvoy/bold','https://marriott.chase.com/bold/benefits'], required: ['annualFee','earn','benefitTags','hotelStatus.automaticTier','hotelStatus.annualNights'] },
    marriott_boundless: { urls: ['https://creditcards.chase.com/travel-credit-cards/marriott-bonvoy/boundless','https://marriott.chase.com/boundless','https://marriott.chase.com/boundless/benefits'], required: ['annualFee','earn','groupCaps.boundless_everyday','postCapEarn.dining','benefitTags','annualPointCertificates','hotelStatus.automaticTier','hotelStatus.annualNights','hotelStatus.spendBlock','hotelStatus.nightsPerBlock','hotelStatus.spendTier.amount','hotelStatus.spendTier.tier'] },
    marriott_bountiful: { urls: ['https://creditcards.chase.com/travel-credit-cards/marriott-bonvoy/bountiful','https://marriott.chase.com/bountiful'], required: ['annualFee','earn','groupCaps.marriott_bountiful_everyday','postCapEarn.dining','benefitTags','hotelStatus.automaticTier','hotelStatus.annualNights','spendRewards'] },
    marriott_bevy: { urls: ['https://www.marriott.com/credit-cards/marriott-bonvoy-bevy-american-express-card.mi','https://www.americanexpress.com/us/credit-cards/card/marriott-bonvoy-bevy/'], required: ['annualFee','earn','groupCaps.marriott_bevy_everyday','postCapEarn.dining','benefitTags','hotelStatus.automaticTier','hotelStatus.annualNights','spendRewards'] },
    marriott_brilliant: { urls: ['https://www.marriott.com/credit-cards/marriott-bonvoy-brilliant-american-express-card.mi','https://www.americanexpress.com/us/credit-cards/card/marriott-bonvoy-brilliant/','https://global.americanexpress.com/card-benefits/view-all/marriott-bonvoy-brilliant','https://global.americanexpress.com/card-benefits/detail/earned-choice-award/marriott-bonvoy-brilliant'], required: ['annualFee','earn','benefitTags','recurringCredits.dining_credit','multiYearCredits.trusted_traveler','annualPointCertificates','hotelStatus.automaticTier','hotelStatus.annualNights','spendRewards'] },
    hilton_no_fee: { urls: ['https://www.americanexpress.com/us/credit-cards/card/hilton-honors/'], required: ['annualFee','earn','benefitTags','hotelStatus.automaticTier','hotelStatus.spendTier.amount','hotelStatus.spendTier.tier'] },
    hilton_surpass: { urls: ['https://www.americanexpress.com/us/credit-cards/card/hilton-honors-surpass/','https://www.americanexpress.com/en-us/account/get-started/hiltonsurpass/uncover-your-benefits'], required: ['annualFee','earn','benefitTags','recurringCredits.hilton_credit','qualitativeSpendRewards','hotelStatus.automaticTier','hotelStatus.spendTier.amount','hotelStatus.spendTier.tier'] },
    hilton_aspire: { urls: ['https://www.americanexpress.com/us/credit-cards/card/hilton-honors-aspire/','https://global.americanexpress.com/card-benefits/view-all/hilton-aspire','https://global.americanexpress.com/card-benefits/terms/hilton-aspire'], required: ['annualFee','earn','benefitTags','recurringCredits.hilton_resort_credit','recurringCredits.flight_credit','recurringCredits.clear','annualQualitativeCertificates','qualitativeSpendRewards','hotelStatus.automaticTier'] }
  }),
  airlines: Object.freeze({
    delta: { urls: ['https://www.delta.com/us/en/skymiles/medallion-program/how-to-qualify','https://www.delta.com/us/en/skymiles/medallion-program/medallion-benefits','https://www.delta.com/content/www/en_US/skymiles/medallion-program/choice-benefits/choice-benefits.html'], required: ['thresholds','tierBenefits'] },
    united: { urls: ['https://www.united.com/en/us/fly/mileageplus/premier/qualify.html','https://www.united.com/en/us/fly/mileageplus/premier.html','https://unitedperksplus.united.com/chart.aspx','https://www.nerdwallet.com/travel/learn/guide-to-united-airlines-premier-elite-status'], required: ['thresholds','minimumUnitedSegments','tierBenefits'] },
    american: { urls: ['https://www.aa.com/web/i18n/aadvantage-program/loyalty-points/index.html','https://www.aa.com/web/i18n/aadvantage-program/answers-support/upgrades-for-status-members.html','https://www.aa.com/web/i18n/travel-info/experience/seats/main-cabin-extra.html','https://www.aa.com/web/i18n/travel-info/boarding-process.html','https://www.aa.com/web/i18n/travel-info/partner-airlines/oneworld-airline-partners.html','https://news.aa.com/news/news-details/2026/American-Airlines-maintains-AAdvantage-status-and-reward-levels-for-third-year-in-a-row-AADV-01/default.aspx'], required: ['thresholds','tierBenefits'] },
    southwest: { urls: ['https://www.southwest.com/rapid-rewards/tiers/a-list/','https://www.southwest.com/rapid-rewards/tiers/a-list-preferred/','https://www.southwest.com/rapid-rewards/tiers/companion-pass/'], required: ['thresholds','flightThresholds','tierBenefits','companionPass.qualifyingPoints','companionPass.qualifyingFlights','companionPass.cardBoost','companionPass.unlimited','companionPass.taxesFeesMinOneWay'] }
  }),
  hotels: Object.freeze({
    hyatt: { urls: ['https://world.hyatt.com/content/gp/en/tiers-and-benefits.html','https://world.hyatt.com/content/gp/en/my-account/tiers/discoverist.html','https://world.hyatt.com/content/gp/en/my-account/tiers/explorist.html','https://world.hyatt.com/content/gp/en/my-account/tiers/globalist.html','https://www.nerdwallet.com/travel/learn/complete-guide-to-hyatt-elite-status','https://www.nerdwallet.com/travel/learn/what-you-need-to-know-about-world-of-hyatts-milestone-rewards','https://thepointsguy.com/loyalty-programs/hyatt-milestone-reward/'], required: ['thresholds','tierBenefits','milestoneRewards'] },
    marriott: { urls: ['https://www.marriott.com/loyalty/member-benefits.mi','https://www.marriott.com/loyalty/member-benefits/silver.mi','https://www.marriott.com/loyalty/member-benefits/gold.mi','https://www.marriott.com/loyalty/member-benefits/platinum.mi','https://www.marriott.com/loyalty/member-benefits/titanium.mi','https://www.marriott.com/loyalty/member-benefits/ambassador.mi','https://www.marriott.com/loyalty/terms/default.mi'], required: ['thresholds','tierBenefits'] },
    hilton: { urls: ['https://www.hilton.com/en/hilton-honors/support-faq/','https://www.hilton.com/en/help-center/hilton-honors-benefits/tiers-and-benefits/','https://www.hilton.com/en/hilton-honors/terms/'], required: ['thresholds','diamondReserve','tierBenefits','milestoneRewards'] }
  })
});

export const ALLOWED_CARD_IDS = Object.freeze(Object.keys(ENTITY_SOURCES.cards));
export const ALLOWED_AIRLINE_IDS = Object.freeze(Object.keys(ENTITY_SOURCES.airlines));
export const ALLOWED_HOTEL_IDS = Object.freeze(Object.keys(ENTITY_SOURCES.hotels));
